# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AIShiftScheduler_KE5',
                'doc_host': 'https://kobus78.github.io',
                'git_url': 'https://github.com/kobus78/AIShiftScheduler_KE5',
                'lib_path': 'AIShiftScheduler_KE5'},
  'syms': {'AIShiftScheduler_KE5.core': {'AIShiftScheduler_KE5.core.foo': ('core.html#foo', 'AIShiftScheduler_KE5/core.py')}}}
