# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_loader.ipynb.

# %% auto 0
__all__ = ['load_sick_probs', 'load_merit_probs', 'load_exog_info']

# %% ../nbs/01_loader.ipynb 4
# from collections import namedtuple, defaultdict
# import numpy as np
import pandas as pd
# import matplotlib as mpl
# import matplotlib.pyplot as plt
# from copy import copy
# import time
# import math
# from pprint import pprint
## !pip install -U "ray"
# import ray
# import json

# %% ../nbs/01_loader.ipynb 8
pd.options.display.float_format = '{:,.4f}'.format
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

# %% ../nbs/01_loader.ipynb 10
def load_sick_probs(filename):
  sick_df = pd.read_excel(
      filename,
      sheet_name='SickProbs',
      ## skiprows=3,
      converters={'ResourceId':str}
      )
  return sick_df

# %% ../nbs/01_loader.ipynb 11
def load_merit_probs(filename):
  merit_df = pd.read_excel(
      filename,
      sheet_name='MeritProbs',
      ## skiprows=3,
      converters={'ResourceId':str}
      )
  return merit_df

# %% ../nbs/01_loader.ipynb 12
def load_exog_info(filename):
  exog_info_df = pd.read_excel(
    filename,
    sheet_name='ExogInfo2',
    skiprows=6,
    converters={'volume':int}
    )
  return exog_info_df
